# Generated by Django 4.1 on 2022-08-10 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrgen', '0003_qrcode_delete_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QrCode',
        ),
    ]
