# Generated by Django 4.1 on 2022-08-10 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrgen', '0007_qrcode_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='image',
        ),
    ]
