# Generated by Django 4.1 on 2022-08-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrgen', '0008_remove_qrcode_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='image',
            field=models.ImageField(blank=True, upload_to='qrcode'),
        ),
    ]
