# Generated by Django 4.1 on 2022-08-10 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrgen', '0011_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QrCode',
        ),
    ]
