# Generated by Django 4.1 on 2022-08-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrgen', '0013_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='color',
            field=models.CharField(default='black', max_length=40),
        ),
    ]
