# Generated by Django 4.1 on 2022-08-12 02:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qrgen', '0016_send_mail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text_Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('text', models.TextField(max_length=250)),
                ('image', models.ImageField(blank=True, upload_to='qrcode')),
                ('color', models.CharField(default='black', max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
