# Generated by Django 4.1 on 2022-08-12 03:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qrgen', '0017_text_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=100)),
                ('website', models.URLField()),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='qrcode')),
                ('color', models.CharField(default='black', max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
