# Generated by Django 4.1 on 2022-08-12 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrgen', '0018_contact_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_details',
            old_name='name',
            new_name='contact_name',
        ),
    ]
