# Generated by Django 4.1 on 2022-08-12 03:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qrgen', '0019_rename_name_contact_details_contact_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image_Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.TextField(max_length=100)),
                ('img', models.ImageField(upload_to='')),
                ('image', models.ImageField(blank=True, upload_to='qrcode')),
                ('color', models.CharField(default='black', max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
