# Generated by Django 4.1 on 2022-08-12 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrgen', '0020_image_upload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image_Upload',
        ),
    ]
