# Generated by Django 4.1 on 2022-08-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrgen', '0021_delete_image_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='create_link',
            name='id',
        ),
        migrations.AddField(
            model_name='create_link',
            name='Create_link_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
