# Generated by Django 4.1 on 2022-08-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrgen', '0022_remove_create_link_id_create_link_create_link_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_link',
            name='Create_link_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False, unique=True),
        ),
    ]
