# Generated by Django 4.1 on 2022-08-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrgen', '0023_alter_create_link_create_link_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_link',
            name='Create_link_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
