# Generated by Django 4.1 on 2022-08-12 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrgen', '0024_alter_create_link_create_link_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Create_link',
        ),
    ]
