# Generated by Django 4.1 on 2022-08-14 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrgen', '0026_create_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='create_link',
            old_name='image',
            new_name='qr_image',
        ),
    ]
