# Generated by Django 4.1 on 2022-08-15 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrgen', '0028_rename_image_contact_details_qr_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='send_mail',
            name='qr_image',
            field=models.ImageField(blank=True, upload_to='mail_qrcode'),
        ),
        migrations.AlterField(
            model_name='text_message',
            name='qr_image',
            field=models.ImageField(blank=True, upload_to='text_qrcode'),
        ),
    ]
