# Generated by Django 4.1 on 2022-08-15 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrgen', '0029_alter_send_mail_qr_image_alter_text_message_qr_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_details',
            old_name='qr_image',
            new_name='qr_Image',
        ),
        migrations.RemoveField(
            model_name='send_mail',
            name='qr_image',
        ),
        migrations.RemoveField(
            model_name='text_message',
            name='qr_image',
        ),
        migrations.AddField(
            model_name='send_mail',
            name='Qr_Image',
            field=models.ImageField(blank=True, upload_to='qrcode'),
        ),
        migrations.AddField(
            model_name='text_message',
            name='Qr_image',
            field=models.ImageField(blank=True, upload_to='qrcode'),
        ),
    ]
